sudo: required
language: node_js

node_js:
    - "8"


services: 
    - docker

before_install:
    - docker build -t rahulrk9/docker-react -f Dockerfile.dev .

scripts:
    - docker run rahulrk9/docker-react npm run test -- --coverage